---
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped

  api:
    build:
      context: .
    ports:
      - 80:8080
    environment:
      MYSQL_PASSWORD: password
      MYSQL_URL: db
    restart: unless-stopped

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ${HOME}/db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project
