---
services:
  api:
    build:
      context: .
    ports:
      - 80:8080
    environment:
      MYSQL_PASSWORD: password
    restart: unless-stopped

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ${HOME}/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project
